[package]
name = "hypercore"
version = "0.11.0"
license = "MIT OR Apache-2.0"
description = "Secure, distributed, append-only log"
documentation = "https://docs.rs/hypercore"
repository = "https://github.com/datrs/hypercore"
readme = "README.md"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
keywords = ["dat", "p2p", "stream", "feed", "merkle"]
categories = [
  "asynchronous",
  "concurrency",
  "cryptography",
  "data-structures",
  "encoding",
]
edition = "2018"

[dependencies]
blake2-rfc = "0.2.18"
byteorder = "1.3.4"
ed25519-dalek = "1.0.0-pre.3"
anyhow = "1.0.26"
flat-tree = { version = "4.1.0", git = "https://github.com/bltavares/flat-tree", branch = "usize-to-u64" }
lazy_static = "1.4.0"
memory-pager = "0.9.0"
merkle-tree-stream =  { version = "0.11.0", git = "https://github.com/bltavares/merkle-tree-stream", branch = "usize-to-u64" }
pretty-hash = "0.4.1"
rand = "0.7.3"
random-access-disk = { version = "1.0.0", git = "https://github.com/bltavares/random-access-disk", branch = "failure-into-stderr" }
random-access-memory = { version = "1.1.0", git = "https://github.com/bltavares/random-access-memory", branch = "failure-into-stderr" }
random-access-storage = "3.0.0"
sha2 = "0.8.1"
sleep-parser = "0.8.0"
sparse-bitfield = "0.11.0"
tree-index = { version = "0.5.0", git = "https://github.com/bltavares/tree-index", branch = "usize-to-u64" }
bitfield-rle = "0.1.1"

[dev-dependencies]
quickcheck = "0.9.2"
data-encoding = "2.2.0"
remove_dir_all = "0.5.2"
tempfile = "3.1.0"
async-std = "1.5.0"
